import { strict as assert } from "assert";
import fs from "fs";
import { client as redisClient } from "../services/cacheServiceRedis.js";
import { getSDsFromPresentationDef } from "../utils/vpHeplers.js";
import { validateMdlClaims, verifyMdlToken } from "../utils/mdlVerification.js";

describe("mDL VP Token Verification", () => {
  const testPayload3 =
    "o2d2ZXJzaW9uYzEuMGlkb2N1bWVudHOBo2dkb2NUeXBleBt1cm46ZXUuZXVyb3BhLmVjLmV1ZGk6cGlkOjFsaXNzdWVyU2lnbmVkompuYW1lU3BhY2VzoXgbdXJuOmV1LmV1cm9wYS5lYy5ldWRpOnBpZDoxiNgYWGSkaGRpZ2VzdElEAHFlbGVtZW50SWRlbnRpZmllcmpnaXZlbl9uYW1lbGVsZW1lbnRWYWx1ZWVIYW5uYWZyYW5kb21YIOWipvuDaOC9gvgDx03t2lIr2LGGhkHDnyQQSm1R_ZJx2BhYa6RoZGlnZXN0SUQBcWVsZW1lbnRJZGVudGlmaWVya2ZhbWlseV9uYW1lbGVsZW1lbnRWYWx1ZWtNYXRrYWxhaW5lbmZyYW5kb21YIHfAeoi-XkGFXfX0QydCa84L1DIOTnmA7rktygaVTPlp2BhYaaRoZGlnZXN0SUQCcWVsZW1lbnRJZGVudGlmaWVyamJpcnRoX2RhdGVsZWxlbWVudFZhbHVlajIwMDUtMDctMDFmcmFuZG9tWCCfpQcbY86mXcbnX2g2TRNLnqdOnxZ5f8kAh0RM2Wh2ENgYWGCkaGRpZ2VzdElEA3FlbGVtZW50SWRlbnRpZmllcmthZ2Vfb3Zlcl8xOGxlbGVtZW50VmFsdWX1ZnJhbmRvbVgg0KQTHcJQNB1VuxBlxtQLQx6QsksL1d7xVWvR_7jYA9jYGFhqpGhkaWdlc3RJRARxZWxlbWVudElkZW50aWZpZXJrZXhwaXJ5X2RhdGVsZWxlbWVudFZhbHVlajIwMjYtMDctMDJmcmFuZG9tWCAb-L7uyCLBnulQUjgggs98n0jrEMZ75tppQXWPlKEzctgYWHmkaGRpZ2VzdElEBXFlbGVtZW50SWRlbnRpZmllcnFpc3N1aW5nX2F1dGhvcml0eWxlbGVtZW50VmFsdWVzVUFlZ2VhbiBUZXN0IElzc3VlcmZyYW5kb21YIDHVn43x6zfO6JTJPc5P_4cwthwe2eX4RY1c7SQ8f4bH2BhYZqRoZGlnZXN0SUQGcWVsZW1lbnRJZGVudGlmaWVyb2lzc3VpbmdfY291bnRyeWxlbGVtZW50VmFsdWViRklmcmFuZG9tWCBHIoMSTZExxMQKqJe9FB6hyrfECCUL2MKL8oEKEbjmGdgYWGmkaGRpZ2VzdElEB3FlbGVtZW50SWRlbnRpZmllcmppc3N1ZV9kYXRlbGVsZW1lbnRWYWx1ZWoyMDI1LTA3LTAyZnJhbmRvbVggn3P5QXNQ4vlA3pi3jUtgqB9L3SiJDcv0adK0PAJ_wO1qaXNzdWVyQXV0aIRDoQEmogT3GCGBWQH5MIIB9TCCAZygAwIBAgIUNTSpz-O9IU-W8tCLxrw_cD33QPQwCgYIKoZIzj0EAwIwUzELMAkGA1UEBhMCR1IxCzAJBgNVBAgMAkdSMRAwDgYDVQQKDAdVQWVnZWFuMRAwDgYDVQQLDAdVQWVnZWFuMRMwEQYDVQQDDAp1YWVnZWFuLmdyMB4XDTI1MDIyNDEwMTYxOFoXDTI2MDIyNDEwMTYxOFowUzELMAkGA1UEBhMCR1IxCzAJBgNVBAgMAkdSMRAwDgYDVQQKDAdVQWVnZWFuMRAwDgYDVQQLDAdVQWVnZWFuMRMwEQYDVQQDDAp1YWVnZWFuLmdyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdMLtMHM-bYdiJRHJmfA7ypihS8JDAmci4q3FOeLy6mDxleHd06wugkVPVjoX74eBHq4GOw6J-dMiKJWdB-Cha6NOMEwwKwYDVR0RBCQwIoINZHNzLmFlZ2Vhbi5ncoIRd3d3LmRzcy5hZWdlYW4uZ3IwHQYDVR0OBBYEFFSKW9UeWwZQqehF-I2VS8J9pSfLMAoGCCqGSM49BAMCA0cAMEQCIGm8kv8fPaBeB_pxZLSpsQw5e_DGc68vIkyrqt3GjxTRAiB0cyG1tBkKFTk5sEHxsc-nvBBCkqRZkut7PrzRosllr1kCadgYWQJkuQAGZ3ZlcnNpb25jMS4wb2RpZ2VzdEFsZ29yaXRobWdTSEEtMjU2bHZhbHVlRGlnZXN0c6F4G3VybjpldS5ldXJvcGEuZWMuZXVkaTpwaWQ6MagAWCCh1GiI1xAfbjICunqmoB4lPWC1SU80husv2am-f5_C4gFYIFXwBTImp-8VweRpv7Tk-QAO4g7CiA5Invohi6QF_7ifAlggUb7H4HK2iIyNdRVXUstEC9f5qK-8u8JElNgHrKhNvJYDWCAvzkXxU96kzq1XrFyG6JqeZdtD4spdvHTTsl4c553fYQRYIECbckJgsZBhajRjjkN71DbPTqezcYXVvSBifzv6GhdxBVggjQ1tzUsp9XSgrh16CMG3IWHB-Y3k0pLNk9Sp-s_AQPUGWCB_-6ss_L-0TosntpnpnfS-ZeMXOajbtFXY1xM0XFwCUwdYIBfV74wtFvKKea7ljadWortR3JHn6YwLnXpvpeZSe2GzbWRldmljZUtleUluZm-5AAFpZGV2aWNlS2V5pAECIAEhWCB4IDGTIhmc2fKmrSqpE3tnOu9mu9tKPjT-qOHkub-WlCJYIIzQLqSwotLftVyfVCY_eG6D8qycF0xg7ODi7iAaq-UKZ2RvY1R5cGV4G3VybjpldS5ldXJvcGEuZWMuZXVkaTpwaWQ6MWx2YWxpZGl0eUluZm-5AANmc2lnbmVkwHQyMDI1LTA3LTAyVDE1OjQwOjE2Wml2YWxpZEZyb23AdDIwMjUtMDctMDJUMTU6NDA6MTZaanZhbGlkVW50aWzAdDIwMjYtMDctMDJUMTU6NDA6MTZaWEDeB7y8dszinrz1bKo03q2BSU0YPirg4BvXvZpghnJlQHXwv-YsxrUxJevg4Y_08fWGqSaQ-o2WpqMyM6ORT4b5bGRldmljZVNpZ25lZKJqbmFtZVNwYWNlc9gYQaBqZGV2aWNlQXV0aKFvZGV2aWNlU2lnbmF0dXJlhEOhASag9lhAkD-qd0XtjhHOIkLH2b9IjnbvdpRj1tHvm337X8qgcJjt0Bs-A04GFatUDDoxqKdpPyPHXysVuPLqvSjEmhsubWZzdGF0dXMA";

  it("should verify mDL token using verifyMdlToken function with selective disclosure new PEX", async () => {
    const vpToken = testPayload3; //"eyJhbGciOiJSUzI1NiIsInR5cCI6Im9hdXRoLWF1dGh6LXJlcStqd3QiLCJ4NWMiOlsiTUlJRHZqQ0NBcWFnQXdJQkFnSVVjdzJyVzlVZ2pXQjl0Q1l5NlBHYjh1RjNHc1V3RFFZSktvWklodmNOQVFFTEJRQXdjVEVMTUFrR0ExVUVCaE1DUlZVeER6QU5CZ05WQkFnTUJrZFNSVVZEUlRFUE1BMEdBMVVFQnd3R1IxSkZSVU5GTVJBd0RnWURWUVFLREFkVlFXVm5aV0Z1TVJZd0ZBWURWUVFMREExSlZDQkVaWEJoY25SdFpXNTBNUll3RkFZRFZRUUREQTFrYzNNdVlXVm5aV0Z1TG1keU1CNFhEVEkwTVRBeE5qRXlNall6TmxvWERUSTFNVEF4TmpFeU1qWXpObG93Y1RFTE1Ba0dBMVVFQmhNQ1JWVXhEekFOQmdOVkJBZ01Ca2RTUlVWRFJURVBNQTBHQTFVRUJ3d0dSMUpGUlVORk1SQXdEZ1lEVlFRS0RBZFZRV1ZuWldGdU1SWXdGQVlEVlFRTERBMUpWQ0JFWlhCaGNuUnRaVzUwTVJZd0ZBWURWUVFEREExa2MzTXVZV1ZuWldGdUxtZHlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQThZckNBeXl2cTZ2UmdmU2NpYTZ2czlYQm9QUURVZXJqY012eVhVRUxuUEMzdDh5dGN0QVBxUnBFRXVMSkEwK0RqbjVWSWVTZUVkdFhnQ2tIdkRqOXBRTnFxbTVKUFlQR3NiMVV5QUtOZEZPYXpLWUsvdDB3UDhwQjdQVE9zdDY2SFlqcndNL0VUeWI2aFZlYnZkS3pOWUticW04Vkkvb1pRdEJ3cXhHaVlqNzcyOUR2Qnd2c3ErbUtIdElQYmhaSm5rZ3FFM25JTTlQeEM2ZURhamIybHdQUXFzM3VvK3VPWmlxSjlIMDhYek5BR08yd0pVQnVXTXRhalNUQlI1NHNiRXVNOFJTUDV2Zi8rNGJpcDZSZ3RRV1dSNG04VG52WTFiN21sMHRJYVVRbUNRd29MNnhRbm1rSjkvL2p4eG94UWhkd3lRS2RwbG9mamJkVWdRQjNKUUlEQVFBQm8wNHdUREFyQmdOVkhSRUVKREFpZ2cxa2MzTXVZV1ZuWldGdUxtZHlnaEYzZDNjdVpITnpMbUZsWjJWaGJpNW5jakFkQmdOVkhRNEVGZ1FVVDA4NVRLOGtyTFpVVmNMNFNIMmw2TEV3ZzN3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCM09zNFh4YXhkRzhRMmVBY2NwS29EaklDalJ4Z1RRNlVGa1NCMjFHT0Y1Uy9DdEhLT2NNaFl0V0RPZDRHZVFZNUxyQ2lkcWNUN094cTBxZld3eThqcUhjR1NTeVJxdFo0THpYeXpLbW0vc2wwbFpmMGgySnJXU3hrUDhxY3B1NHZtSDFKek9zMXloUFBLblpHUzR2SlJWVEI2SmJSeEZZSFA1dVlrUTU2R2d1QkFGUTBWMHpaME1QZWR1Rm1KTC9JQzJFRUpUQ2I1OEJPaHQra2FWSGhHUVBHRDVOdzRobU8vSGkrV2Z5eEpHR2dSdGtwSWxEVDdua1BJVCtyTG9sY1FIWVA2M3FHVWw2UW1xSUxQbzFXZjNXZjdhanNCQ2ZZbTJFS3FDcGRTU3dydExYL3FKNlJ6S3l1YnBTVXgyS0xicXk3ZnVsa0E2dVQ3MVF1U21JWEk9Il19.eyJyZXNwb25zZV90eXBlIjoidnBfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJjbGllbnRfaWQiOiJ4NTA5X3Nhbl9kbnM6ZHNzLmFlZ2Vhbi5nciIsInJlc3BvbnNlX3VyaSI6Imh0dHBzOi8vZHNzLmFlZ2Vhbi5nci9yZmMtaXNzdWVyL2RpcmVjdF9wb3N0L2VjYTkyZGZmLTdkMTQtNDFmZS1hYWY0LWMyMGQ0Y2E5NDExNSIsIm5vbmNlIjoiMDBhZDE5MjYzNmIxNTVlNzYxMDQwZjRkMDA1ZGU3N2IiLCJzdGF0ZSI6ImVjMjY1MmY4OGU0NzY4NzAyZGU3ZjliY2EzYzQ0Y2VmIiwiY2xpZW50X21ldGFkYXRhIjp7ImNsaWVudF9uYW1lIjoiVUFlZ2VhbiBFV0MgVmVyaWZpZXIiLCJsb2dvX3VyaSI6Imh0dHBzOi8vc3R1ZHlpbmdyZWVjZS5lZHUuZ3Ivd3AtY29udGVudC91cGxvYWRzLzIwMjMvMDMvMjUucG5nIiwibG9jYXRpb24iOiJHcmVlY2UiLCJjb3Zlcl91cmkiOiJzdHJpbmciLCJkZXNjcmlwdGlvbiI6IkVXQyBwaWxvdCBjYXNlIHZlcmlmaWNhdGlvbiIsInZwX2Zvcm1hdHMiOnsiZGMrc2Qtand0Ijp7InNkLWp3dF9hbGdfdmFsdWVzIjpbIkVTMjU2IiwiRVMzODQiXSwia2Itand0X2FsZ192YWx1ZXMiOlsiRVMyNTYiLCJFUzM4NCJdfX19LCJpc3MiOiJ4NTA5X3Nhbl9kbnM6ZHNzLmFlZ2Vhbi5nciIsImF1ZCI6Imh0dHBzOi8vc2VsZi1pc3N1ZWQubWUvdjIiLCJwcmVzZW50YXRpb25fZGVmaW5pdGlvbiI6eyJpZCI6ImQ0OWVlNjE2LTBlOGQtNDY5OC1hZmY1LTJhOGEyMzYyNjUyZSIsIm5hbWUiOiJtZGwtcHJvb2YiLCJmb3JtYXQiOnsibXNvX21kb2MiOnsiYWxnIjpbIkVTMjU2IiwiRVMzODQiXX19LCJpbnB1dF9kZXNjcmlwdG9ycyI6W3siaWQiOiJhNTcxZWE0OS05ZDY5LTQyMzUtODY5Mi0zZDdkZGYyMjUzYTkiLCJmb3JtYXQiOnsibXNvX21kb2MiOnsiYWxnIjpbIkVTMjU2IiwiRVMzODQiXX19LCJjb25zdHJhaW50cyI6eyJmaWVsZHMiOlt7InBhdGgiOlsiJFsnb3JnLmlzby4xODAxMy41LjEnXVsnc3VybmFtZSddIl19LHsicGF0aCI6WyIkWydvcmcuaXNvLjE4MDEzLjUuMSddWydnaXZlbl9uYW1lJ10iXX0seyJwYXRoIjpbIiRbJ29yZy5pc28uMTgwMTMuNS4xJ11bJ3Bob25lJ10iXX1dfX1dLCJkb2NfdHlwZSI6Im9yZy5pc28uMTgwMTMuNS4xLm1ETCJ9fQ.rE6u7NgKjE7nqn1HaGRDJw2gBd3WDwU3BKeEsbcNDYq6mUd3V0QLkQ9zkdpC1q6pxbNzY9k17SKBP7tJc6DHVLQbc0QfxisRS0I6Kf6jlU9B6lznIN_Ve9A6uuz_7M6-ZfsiS76WdqpnOd5SHJAx3pmqO0-FeFAkpyxBfZD5GEAJymSoBqlJfzG-XvJNT3awiMC-OTnhlrOXxfyVlOu6fBz6ATB0l80nMRo_WdjDQidxCYwZj8izadDSkVRnx_otqh5EmpGu-YG12UQJKD-nQtNiiLliNrPRbshpgJCz7z7L5zCiDX0f563FgG-khfGlV32MzTPiM8JUj1JkgVtXew"
    console.log("\n=== Testing verifyMdlToken with Selective Disclosure ===");

    try {
      // Load presentation definition to get selective disclosure fields
      const presentationDefinitionRaw = fs.readFileSync(
        "./data/presentation_definition_mdl.json",
        "utf-8"
      );
      const presentation_definition_mdl = JSON.parse(
        presentationDefinitionRaw
      );
      const sdsRequested = getSDsFromPresentationDef(
        presentation_definition_mdl
      );

      console.log(
        "🔍 Selective Disclosure Fields from Presentation Definition:"
      );
      console.log(JSON.stringify(sdsRequested, null, 2));

      // Set up verification options
      const verificationOptions = {
        requestedFields: sdsRequested, // Apply selective disclosure if requested
        validateStructure: true,
        includeMetadata: true,
      };

      // Call verifyMdlToken function
      const mdocResult = await verifyMdlToken(vpToken, verificationOptions);

      console.log("\n📋 mDL Verification Result:");
      console.log(JSON.stringify(mdocResult, null, 2));

      // Extract and print claims
      const claims = mdocResult.claims;
      console.log("\n🎯 Extracted Claims:");
      console.log(JSON.stringify(claims, null, 2));

      // Validate the result
      assert.ok(mdocResult.success, "Verification should be successful");
      assert.ok(claims, "Claims should be present");
      assert.strictEqual(
        mdocResult.docType,
        "urn:eu.europa.ec.eudi:pid:1",
        "Should be an mDL document"
      );

      // Validate that all requested fields are present
      const validationResult = validateMdlClaims(claims, sdsRequested);
      assert.ok(
        validationResult,
        "All requested fields should be present in claims"
      );

      console.log("\n✅ Test completed successfully!");

      return mdocResult;
    } catch (error) {
      console.error("❌ Test failed:", error.message);
      throw error;
    }
  });
});

after(async () => {
  console.log("Closing Redis connection...");
  await redisClient.quit();
  console.log("Redis connection closed.");
});
