export const TRUST_REASON_CODES = Object.freeze({
  BOOTSTRAP_UNTRUSTED: "BOOTSTRAP_UNTRUSTED",
  LIST_SIGNATURE_INVALID: "LIST_SIGNATURE_INVALID",
  LIST_PROFILE_INVALID: "LIST_PROFILE_INVALID",
  LIST_STALE: "LIST_STALE",
  LIST_NOT_YET_VALID: "LIST_NOT_YET_VALID",
  POINTER_NOT_FOUND: "POINTER_NOT_FOUND",
  REFERENCED_LIST_UNAVAILABLE: "REFERENCED_LIST_UNAVAILABLE",
  REFERENCED_LIST_SIGNATURE_INVALID: "REFERENCED_LIST_SIGNATURE_INVALID",
  ENTITY_NOT_LISTED: "ENTITY_NOT_LISTED",
  ENTITY_STATUS_INVALID: "ENTITY_STATUS_INVALID",
  ANCHOR_MISMATCH: "ANCHOR_MISMATCH",
  IDENTITY_MISMATCH: "IDENTITY_MISMATCH",
  UNSUPPORTED_LIST_TYPE: "UNSUPPORTED_LIST_TYPE",
  TRUST_EVALUATION_INDETERMINATE: "TRUST_EVALUATION_INDETERMINATE",
  TRUSTED: "TRUSTED",
  INVALID_REQUEST: "INVALID_REQUEST",
  UNSUPPORTED_FRAMEWORK: "UNSUPPORTED_FRAMEWORK",
  UNSUPPORTED_ROLE: "UNSUPPORTED_ROLE",
  REVOCATION_UNKNOWN: "REVOCATION_UNKNOWN",
});

export class TrustListError extends Error {
  constructor(message, reasonCode, details = {}) {
    super(message);
    this.name = "TrustListError";
    this.reasonCode = reasonCode;
    this.details = details;
  }
}
