# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/dev-i4mlab.aegean.gr
cert = /etc/letsencrypt/live/dev-i4mlab.aegean.gr/cert.pem
privkey = /etc/letsencrypt/live/dev-i4mlab.aegean.gr/privkey.pem
chain = /etc/letsencrypt/live/dev-i4mlab.aegean.gr/chain.pem
fullchain = /etc/letsencrypt/live/dev-i4mlab.aegean.gr/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 023adb351b5c6ec7fd0b0265efa18d29
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
dev-i4mlab.aegean.gr = /var/www/certbot
